name: uber_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.16.0
  country_code_picker:
  firebase_auth: ^3.3.18
  flutter_bloc:
  sms_autofill: ^2.2.0
  http:
  bloc:
  hydrated_bloc:
  equatable:
  get_it:
  get: 4.6.1
  path_provider:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

