// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASh3we74FvLL-NpT33H02_0sLEEu0_dzA',
    appId: '1:936797180374:web:10464a79ac3f30962f5477',
    messagingSenderId: '936797180374',
    projectId: 'flutter-uber-clone-01',
    authDomain: 'flutter-uber-clone-01.firebaseapp.com',
    storageBucket: 'flutter-uber-clone-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bqPq6dacL5Gbv8QwhQogfZH--ua9hAQ',
    appId: '1:936797180374:android:9cb38a40400921f72f5477',
    messagingSenderId: '936797180374',
    projectId: 'flutter-uber-clone-01',
    storageBucket: 'flutter-uber-clone-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-XrTVhQhSPL9tS-OUJGrMwz7_qPZdReg',
    appId: '1:936797180374:ios:fe47cac73c2c2f872f5477',
    messagingSenderId: '936797180374',
    projectId: 'flutter-uber-clone-01',
    storageBucket: 'flutter-uber-clone-01.appspot.com',
    iosClientId: '936797180374-139qqspq28keaguq8u3stpad2v5pdr71.apps.googleusercontent.com',
    iosBundleId: 'com.sharif.uberClone',
  );
}
